frontend/.env, frontend/src/context/AuthContext.tsx, frontend/src/pages/Auth/SignIn.tsx
FE에서 서로 맞지않는 로그인 요청 JSON 값 변경 및 로그인 테스트
URI 및 요청 JSON 값 변경
JWT 토큰 테스트 진행
- 1. 로그인 페이지에서 사용자 이름과 비밀번호 입력 후 로그인 요청 전송
- 2. 서버로부터 성공적인 응답 (`200 OK`)을 받았으나, JWT 토큰이 응답에 포함되지 않음
- 3. 클라이언트 브라우저 `localStorage`에 저장된 값은 `undefined`
서버가 성공적으로 로그인하면, JWT 토큰을 포함한 응답이 반환되어야 합니다.
응답 데이터는 다음과 같은 형식
```json
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
```
- 로그인 아이디 및 비밀번호가 인증 실패 시 응답 상태 코드 추가
HTTP 상태 코드:
401 Unauthorized: 인증 실패 시 주로 사용되는 상태 코드입니다.
응답 메시지:
응답 본문에는 실패 이유(아이디 또는 비밀번호가 틀린 경우 등)가 JSON 형식으로 포함
```json
"error": "Invalid username or password"
```
Closes #60
=> #60 refactor: uri 주소 변경 및 로그인 json 값 수정

frontend/src/config/apiConfig.ts, frontend/src/pages/Main/Main.tsx, frontend/src/pages/Main/MainStyle.ts
- 논문 4개를 서버에서 가져옴
- 각 공지탭마다 5개씩 공지사항을 서버에서 가져옴
https://github.com/user-attachments/assets/1ca8658b-a87b-40a9-9f9a-de8bdaa7376a
- 서버에 저장된 논문 이미지 링크가 유효하지 않아서(더미데이터) 이미지가 뜨지 않음
- 논문 조회 페이지 구현 후 논문마다 링크 연결 필요
- 세미나 조회 페이지 구현 후 최신 세미나 버튼에 링크 연결 필요
- 논문, 공지사항 최신순으로 정렬 필요
Closes #101
=> [FE] 메인페이지 api 연결

frontend/src/pages/SeminarRoom/Reservation.tsx
캘린더 예약 현황 렌더링 테스트 
PR(Pull Request) 문서를 작성해드리겠습니다:
```markdown
세미나실 예약 시스템의 캘린더 뷰에 예약 현황을 시각적으로 표시하는 기능을 구현했습니다.
```typescript
interface Reservation {
id: number;
roomId: string;
date: string;
startTime: string;
endTime: string;
userName: string;
purpose: 'SEMINAR' | 'STUDY' | 'MEETING' | 'OTHER';
contact: string;
department?: string;
}
```
- 날짜별 예약 현황 시각화
- 예약 목적별 색상 구분
- 룸별 필터링 지원
- 예약 시간대 표시
- 예약이 있는 날짜 강조 표시
- 컴팩트한 예약 정보 표시
- 직관적인 색상 코드 적용
[캘린더 뷰 스크린샷 첨부]
- 현재는 더미데이터를 사용중이며, 추후 API 연동 예정
- 예약 생성/수정/삭제 기능은 다음 PR에서 구현 예정
=> #117 test: 더미데이터 사용 캘린더 예약 현황 렌더링 테스트

.github/workflows/main.yml, backend/Dockerfile, backend/src/main/java/org/example/backend/board/controller/BoardController.java
main.yml
```
name: Backend CI/CD using GitHub Actions & Docker
on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]
jobs:
build:
runs-on: ubuntu-latest
permissions:
contents: read
steps:
- uses: actions/checkout@v4
- name: Set up JDK 21
uses: actions/setup-java@v4
with:
java-version: '21'
distribution: 'temurin'
- name: Create backend configuration files
run: |
mkdir -p ./backend/src/main/resources
cd ./backend/src/main/resources
echo "${{ secrets.APPLICATION_YML }}" > application.yml
echo "${{ secrets.APPLICATION_AWS_YML }}" > application-aws.yml
- name: Setup Gradle
uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
- name: Build Backend
run: |
cd backend
chmod +x ./gradlew
./gradlew build -x test
- name: Docker build & push
run: |
docker login -u …
```
=> [BE] CI / CD 구축

frontend/src/components/Footer/FooterStyle.ts
- `FooterContainer`: 세로 정렬로 변경
- `Address`: 텍스트를 중앙 정렬하고 글씨 크기를 조정
- `SightMap`: 그리드로 변경
- `SightMapContent`: 숨김
- `Copyright`: 중앙 정렬 및 텍스트 크기 축소
- `AdminButton`: 버튼 크기와 아이콘 크기 조정
- 반응형 디자인은 CSS @media 쿼리를 사용
**[태블릿]**
<br>
**[모바일]**
Closes #158
=> [FE] 푸터 반응형 디자인 레이아웃 개선

backend/src/main/java/org/example/backend/seminarRoom/domain/SeminarRoom.java, backend/src/main/java/org/example/backend/seminarRoom/domain/controller/SeminarRoomController.java, backend/src/main/java/org/example/backend/seminarRoom/domain/dto/SeminarRoomReqDto.java, backend/src/main/java/org/example/backend/seminarRoom/domain/dto/SeminarRoomResDto.java, backend/src/main/java/org/example/backend/seminarRoom/exception/SeminarRoomException.java, backend/src/main/java/org/example/backend/seminarRoom/exception/SeminarRoomExceptionType.java, backend/src/main/java/org/example/backend/seminarRoom/repository/SeminarRoomRepository.java, backend/src/main/java/org/example/backend/seminarRoom/service/SeminarRoomService.java, backend/src/main/java/org/example/backend/timetable/controller/TimetableController.java, backend/src/main/java/org/example/backend/timetable/domain/Timetable.java, backend/src/main/java/org/example/backend/timetable/domain/WeekDay.java, backend/src/main/java/org/example/backend/timetable/domain/dto/TimetableReqDto.java, backend/src/main/java/org/example/backend/timetable/domain/dto/TimetableResDto.java, backend/src/main/java/org/example/backend/timetable/exception/TimetableException.java, backend/src/main/java/org/example/backend/timetable/exception/TimetableExceptionType.java, backend/src/main/java/org/example/backend/timetable/repository/TimetableRepository.java, backend/src/main/java/org/example/backend/timetable/service/TimetableService.java, backend/src/main/resources/data.sql
- 세미나실 등록/조회/수정/삭제
- 수용 인원, 위치, 이미지 등 관리
- 각 세미나실별 예약 현황 관리
- 정기 수업 시간표 등록/조회/수정/삭제
- 요일별 수업 시간 관리 (월~일)
- 기간별 수업 일정 관리
```sql
CREATE TABLE seminar_room (
seminar_room_id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255),
person_capacity INTEGER,
place VARCHAR(255),
image VARCHAR(255)
);
```
```sql
CREATE TABLE timetable (
timetable_id BIGINT PRIMARY KEY AUTO_INCREMENT,
start_date DATE,
end_date DATE,
start_time TIME,
end_time TIME,
week_day VARCHAR(7),
seminar_room_id BIGINT,
FOREIGN KEY (seminar_room_id) REFERENCES seminar_room(seminar_room_id)
);
```
```
POST   /api/seminar-rooms      - 세미나실 생성
GET    /api/seminar-rooms/{id} - 세미나실 조회
PUT    /api/seminar-rooms/{id} - 세미나실 수정
DELETE /api/seminar-rooms/{id} - 세미나실 삭제
```
```
POST   /api/timetables         - 시간표 생성
GET …
```
=> [BE] 세미나실, 시간표 CRUD 설계

backend/backup.sql, backend/src/main/java/org/example/backend/board/controller/BoardController.java, backend/src/main/java/org/example/backend/board/domain/dto/BoardReqDto.java, backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java, backend/src/main/java/org/example/backend/board/domain/entity/Board.java, backend/src/main/java/org/example/backend/board/exception/BoardExceptionType.java, backend/src/main/java/org/example/backend/board/service/BoardService.java, backend/src/main/java/org/example/backend/global/config/StringListConverter.java, backend/src/main/resources/data.sql
- Board 엔티티 내 file 필드 수정
- `String file` ->  `List<String> fileList`
- create, update 메서드 수정
노션 링크: https://www.notion.so/Board-cbe98e5970d445fdb835033f8f77fc21?pvs=4
Closes #172
=> [BE] Board 파일 업로드 기능 추가

backend/src/main/java/org/example/backend/board/domain/dto/BoardReqDto.java, backend/src/main/java/org/example/backend/board/domain/entity/Category.java, backend/src/main/java/org/example/backend/board/exception/BoardExceptionType.java, backend/src/main/java/org/example/backend/board/service/BoardService.java, backend/src/main/java/org/example/backend/professor/domain/dto/professor/ProfessorReqDto.java, backend/src/main/java/org/example/backend/thesis/domain/dto/ThesisReqDto.java
- reqDto에서 파일 필드 swagger 상 숨김 처리
- Board category 필드를 필수에 추가
Closes #190
=> [BE] [REFACTOR] reqDto에서 파일 필드 숨김 및 Board category 필드를 필수에 추가

frontend/src/pages/Main/Main.tsx
- useNavigate를 이용해 메인 페이지에서 특정 공지사항을 클릭 시 해당 공지사항 페이지로 이동하는 기능 구현 
Closes #200
=> [FE] 메인 페이지에서 특정 공지사항 클릭 시 해당 공지사항 페이지로 이동

frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx, frontend/src/pages/News/NoticeBoard/hooks/useNoticeBoard.ts, frontend/src/pages/News/NoticeBoard/types/notice.types.ts
명세에 맞게 정렬기능 추가
기본 리스트 렌더링 시 등록일 최신순으로 정렬됨
게시글의 프로퍼티명과 정렬 기능의 프로퍼티명 다름
게시글 : createDate
정려 : createdDate
=> [FE] [FEAT] 게시판 리스트 등록일 정렬 기능 추가 

backend/backup.sql, backend/src/main/java/org/example/backend/news/controller/NewsController.java, backend/src/main/java/org/example/backend/news/domain/dto/NewsReqDto.java, backend/src/main/java/org/example/backend/news/domain/dto/NewsResDto.java, backend/src/main/java/org/example/backend/news/domain/entity/News.java, backend/src/main/java/org/example/backend/news/exception/NewsException.java, backend/src/main/java/org/example/backend/news/exception/NewsExceptionType.java, backend/src/main/java/org/example/backend/news/repository/NewsRepository.java, backend/src/main/java/org/example/backend/news/service/NewsService.java, backend/src/main/resources/data.sql
뉴스 CRUD API 생성
노션 명세서: https://www.notion.so/CRUD-API-12129fa4a9c74e0498fa88c11a344593?pvs=4
Closes #236
=> [BE] [FEAT] 뉴스 CRUD API 생성

backend/src/main/java/org/example/backend/board/controller/BoardController.java, backend/src/main/java/org/example/backend/board/repository/BoardRepository.java, backend/src/main/java/org/example/backend/board/service/BoardService.java
- 동일 사용자가 동일 게시글을 반복 조회해도 조회수가 증가하지 않도록 쿠키를 활용한 중복 체크를 구현.
- 동시성 문제를 방지하기 위해 데이터베이스 레벨에서 조회수 증가를 처리.
- 조회수 증가 로직에서 발생할 수 있는 동시성 문제를 해결하기 위해 **데이터베이스 직접 업데이트** 방식을 사용.
- 이를 통해 정확한 조회수가 반영되도록 보장.
---
- 서버에서 사용자의 세션에 조회한 게시글 ID를 저장하여 중복 조회를 방지.
- 예: `session.setAttribute("viewedPosts", Set<Long>);`
- 사용자의 상태를 서버에서 관리하므로 높은 신뢰성을 보장.
- **서버 과부하**: 많은 사용자가 접속하면 세션 데이터를 관리하기 위한 서버 메모리 사용량이 증가.
- **스케일링 어려움**: 서버가 분산 환경(클러스터링)에서 동작할 경우, 세션 동기화나 중앙 관리가 필요.
---
- 사용자 브라우저에 쿠키를 저장하여 이미 조회한 게시글을 확인합니다.
- 예: `Cookie("postView", "[1]_[2]_[3]")`
- **서버 과부하 방지**: 조회 상태를 클라이언트(브라우저)에서 관리하므로 서버 메모리를 사용하지 않습니다.
- 브라우저 의존적: 사용자가 쿠키를 차단하거나 삭제하면 동작이 제한됩니다.
- 데이터 크기 제한: 브라우저에서 허용하는 쿠키 크기 제한(약 4KB)이 존재합니다.
---
1. **서버 과부하 방지**
- 세션 기반 로직은 서버 메모리를 점유하기 때문에 많은 사용자가 접속하는 환경에서는 서버 과부하가 발생 가능.
- 쿠키 기반 로직은 클라이언트에서 상태를 …
=> feat : 조회수 로직 추가

frontend/src/AppContent.tsx, frontend/src/components/Footer/Footer.tsx, frontend/src/components/Header/Navigation/Navigation.tsx, frontend/src/components/Header/Navigation/NavigationStyle.ts, frontend/src/components/Header/constants.ts, frontend/src/components/NewsSlider/NewsCard.tsx, frontend/src/components/NewsSlider/NewsSlider.tsx, frontend/src/components/NewsSlider/NewsSliderStyle.ts, frontend/src/components/NewsSlider/SliderControls.tsx, frontend/src/config/apiConfig.ts, frontend/src/constants/colors.ts, frontend/src/constants/pageContents.ts, frontend/src/hooks/useScrollToTop.ts, frontend/src/pages/Main/Main.tsx, frontend/src/pages/Main/MainStyle.ts, frontend/src/pages/News/News/News.tsx, frontend/src/pages/News/News/NewsCreate.tsx, frontend/src/pages/News/News/NewsCreateStyle.ts, frontend/src/pages/News/News/NewsDetail.tsx, frontend/src/pages/News/News/NewsDetailStyle.ts, frontend/src/pages/News/News/NewsEdit.tsx, frontend/src/pages/News/News/NewsStyle.ts, frontend/src/pages/News/NoticeBoard/hooks/useNoticeBoard.ts
새로운 뉴스 관리 시스템 구현 (CRUD + 슬라이더)
1. **NewsSlider**
- 반응형 뉴스 슬라이더 구현
- 화면 크기에 따른 동적 아이템 개수 조절
- 자동 슬라이드 + 마우스 오버시 일시정지
- 기본 슬라이드 간격: 5초
2. **NewsCard**
- 뉴스 카드 UI 컴포넌트
- 이미지, 제목, 날짜, 조회수 표시
- 이미지 로드 실패시 폴백 처리
3. **News (메인 목록)**
- 페이지네이션 구현
- 관리자용 CRUD 기능
- 반응형 그리드 레이아웃
- React + TypeScript
- styled-components
- moment.js (날짜 처리)
- lucide-react (아이콘)
- react-quill (에디터)
- **뉴스 CRUD**
- 생성/수정시 이미지 업로드
- 리치텍스트 에디터 지원
- AWS S3 이미지 저장
- **슬라이더**
- 반응형 디자인
- 모바일: 1개
- 태블릿: 2개
- 데스크탑: 4개
- 터치/스와이프 지원
1. 이미지 최적화 필요
2. 에러 바운더리 추가 고려
3. 성능 모니터링 추가 검토
```
GET    /api/news          // 목록 조회
GET    /api/news/:id      // 상세 조회
POST   /api/news          // 생성
PUT    /api/news/:id      // 수정
DELETE /api/news/:id      // 삭제
```
- 이미지 업로드 시 5MB 제한
- S3 버킷 권한 설정 필요
Closes #245
=> [FE] [FEAT] 뉴스 CRUD, 뉴스 슬라이더 구현

backend/src/main/java/org/example/backend/jwt/JWTUtil.java, backend/src/main/java/org/example/backend/jwt/LoginFilter.java
=> [BE][FIX] accessToken 만료 시간 수정

frontend/src/pages/Main/Main.tsx
메인 페이지의 공지사항 부분에 작성 날짜가 뜨도록 수정
Closes #279
=> [FE] 메인 페이지의 공지사항에 작성 날짜가 뜨지 않는 현상 수정

backend/build.gradle, backend/src/main/java/org/example/backend/users/dto/SjLoginReq.java, backend/src/main/java/org/example/backend/users/dto/SjUserProfile.java, backend/src/main/java/org/example/backend/users/service/SjAuthService.java, backend/src/test/java/org/example/backend/ControllerTestSupport.java, backend/src/test/java/org/example/backend/SjTest.java, backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
기존 파싱 사이트를 세종대 대양휴머니티칼리지에서 세종대 lms로 변경.
이유
대양휴머니티칼리지는 학생에 특화되있는 반면 lms는 전 구성원의 개인정보관리에 초점이 있어 교직원, 교수도 동등하게 학과, 정보 가져올수있음.
(교수는 테스트X).
테스트 참고. 사용자 객체 생성 -> service 요청.
학생
교직원
전처럼 학교에서 api로직을 변경할경우 다시 수정이 필요함.
커스텀 예외처리 미적용. 왜? -> 필터에서 처리하는 예외처리를 적용시키는게 나아보이는데 이 부분 건의사항이 있음.
로직은 작성했으나 3가지 위치 중 고민중
1. 컨트롤러
2. 인터셉터
3. 필터
전에는 컨트롤러에서 처리를 했으나 인증, 인가 로직은 컨트롤러측에서 처리하는게 아니라고 판단
그래서 2, 3으로 처리하려고 했으나 관리자, 유저도 똑같이 jwt를 사용하는게 맞다고 생각해서 3 필터측에서 처리하는게 가장 적합하다고 생각.
기존에는 유저, 관리자 2개를 나눠서 관리했음. 그러나 로직 중복을 줄이고 jwt rule을 이용해 통합 관리 사용하는게 어떤지?
필터에서 2개의 로직을 처리 후 한번에 관리하는게 깔끔하다고 생각
예상 흐름
-----
필터 req -> 관리자 인지? db 조회
맞다면 관리자 (관리자 jwt 발급)
틀리면 -> 학생인지?
맞다면 학생 (학생 jwt 발급)
틀리면 -> 에러
rule에 맞게 해당 컨트롤러 인가 처리.
의견부탁입니당
Closes #282
=> [BE] 세종대 구성원(교수, 교직원, 학생) 통합 로그인 로직 구현

backend/src/main/java/org/example/backend/board/controller/BoardController.java, backend/src/main/java/org/example/backend/board/repository/BoardRepository.java, backend/src/main/java/org/example/backend/board/service/BoardService.java, backend/src/main/java/org/example/backend/news/controller/NewsController.java, backend/src/main/java/org/example/backend/news/repository/NewsRepository.java, backend/src/main/java/org/example/backend/news/service/NewsService.java, backend/src/main/java/org/example/backend/professor/domain/entity/Professor.java, backend/src/main/java/org/example/backend/seminar/controller/SeminarController.java, backend/src/main/java/org/example/backend/seminar/repository/SeminarRepository.java, backend/src/main/java/org/example/backend/seminar/service/SeminarService.java, backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java, backend/src/main/java/org/example/backend/thesis/repository/ThesisRepository.java, backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
N+1 문제 발생(교수, 논문) 서로 다른 교수를 참조할수록 추가적인 SELECT 쿼리가 많아질 위험이 있음.
fetch join 사용해 즉시 로딩 동작으로 해결
=> [BE][FEAT] 뉴스, 공지, 세미나, 논문 검색기능

backend/src/main/java/org/example/backend/jwt/JWTFilter.java, backend/src/main/java/org/example/backend/users/controller/admin/AdminController.java
결과적으로 SecurityContextHolder 에 잘 저장되고 있었습니다
<br>
테스트 해보다가 loginId는 null이 뜨지만 password는 잘 받아와지는 것을 알 수 있었습니다
그래서 필드 정보 저장에 문제가 있겠거니 생각을 하게 되었고 (정답입니다!)
그쪽 부분을 수정해서 /admin/test에 적어두었으니 예약 시 사용하시면 될 것 같습니다~!
<br>
처음에 springSecurity를 사용해서 로그인 로직을 고려할 때 기본 설정이 username과 password 였던 것을
임의로 loginId로 필드를 수정하여 사용했었는데
그 한번 꼬은 로직에 스스로 헷갈렸습니다..^^
Closes #345
=> [BE] [FEAT] jwt에서 유저 정보 가져오는 기능 구현

backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java, backend/src/main/resources/data.sql
결과적으로, AOP를 이용하는 @PreAuthorize의 경우, 새로운 프록시 객체가 컨트롤러를 감싸게 되어 보안 검증 로직이 수행되기 때문에, 
프록시 객체 생성이 부담으로 다가와 SecurityConfig에서 총괄하여 관리하는 전략을 선택했습니다.
동작 원리: Http 요청을 가로채는 Security Filter에  옵션을 주는 방법
장점:
- 중앙 집중적 관리: 모든 접근 제어 정책이 한 곳(보통 SecurityConfig)에 집중
- 일관성: 모든 엔드포인트에 대해 일관된 보안 규칙을 적용
- 변경 용이성: 보안 정책이 변경될 때, SecurityConfig 하나만 수정하면 되므로 전체 시스템에 빠르게 반영
단점:
- 세밀한 제어 어려움
- 코드와의 분리: 보안 규칙이 컨트롤러 코드와 분리되어 있음
동작 원리: 메소드 수준의 보안을 AOP를 통해 구현
장점:
- 세밀한 제어
- 코드와의 응집도: 메소드 선언 바로 위에 보안 어노테이션이 있어, 이 API가 어떤 권한을 필요로 하는지 명확
- 복잡한 조건 적용 가능
단점:
- 분산 관리: 여러 컨트롤러에 보안 어노테이션이 분산되어 있으면, 전체적인 보안 정책을 한눈에 파악하거나 일괄 변경하기 어려울 수 있음.
- 중복 가능성: 여러 엔드포인트에서 동일한 보안 조건이 반복될 경우, 관리 측면에서 중복 코드 문제가 발생
```java
.requestMatchers(HttpMethod.POST, "/api/news").hasRole("ADMIN")
```
위의 옵션을 주면 일반 사용자가 뉴스를 생성할 수 없다 (Member)
Closes #357
=> [BE] 관리자 계정만 뉴스, 공지사항, 세미나, 논문 생성/수정/삭제 권한 허용

backend/build.gradle, backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java, backend/src/main/java/org/example/backend/users/controller/admin/AdminController.java, backend/src/main/java/org/example/backend/users/exception/admin/AdminExceptionType.java, backend/src/main/java/org/example/backend/users/exception/member/MemberExceptionType.java, backend/src/main/java/org/example/backend/users/repository/UsersRepository.java, backend/src/main/java/org/example/backend/users/service/AdminService.java, backend/src/main/java/org/example/backend/users/service/MemberService.java, backend/src/main/resources/data.sql
관리자 이메일로 임시 비밀번호 발송
테스트 해보고 싶다면 
1. yml 파일에 
username에는 본인 이메일
password는 이메일의 비밀번호
2. adminService
상단에 DEFAULT_FROM_EMAIL 를 본인 이메일로 수정
하시면 테스트 해보실 수 있습니다
Closes #144
=> [BE][FEAT] 관리자 이메일로 임시 비밀번호 발송

backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java, backend/src/main/java/org/example/backend/thesis/exception/ThesisExceptionType.java, backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
- [] 💭 이슈는 등록했나요?
논문 생성 시 교수가 아니라 학사, 석사, 박사 저자도 허용하도록 교수 엔티티가 조회되지 않아도 생성이 가능하게 로직을 변경했음.
=> [BE][FIX] 논문 엔티티 교수 필드 null 허용

frontend/src/components/layout/AppLayout.tsx
fix: 모바일 환경 상단 패딩 로그인 화면만 적용되도록 픽스
=> #389 fix: 모바일 환경 상단 패딩 로그인 화면만 적용되도록 픽스

frontend/craco.config.js, frontend/package.json
개요
이 PR은 빌드 및 배포 과정에서 발생하던 Can't resolve 'crypto' 오류를 해결
webpack 5에서는 이전 버전과 달리 Node.js 코어 모듈에 대한 폴리필을 자동으로 제공하지 않아, axios와 같은 라이브러리가 의존하는 crypto 모듈을 찾지 못하는 문제가 발생했습니다. 이 문제를 해결하기 위해 craco를 도입하고 필요한 폴리필을 구성했습니다.
@craco/craco와 crypto-browserify 패키지 추가
프로젝트 루트에 craco.config.js 설정 파일 생성
package.json의 스크립트를 react-scripts에서 craco로 변경
필요에 따라 추가 폴리필 패키지 설치 (stream-browserify, buffer, util, assert)
```
craco.config.js:
javascriptCopymodule.exports = {
webpack: {
configure: {
resolve: {
fallback: {
crypto: require.resolve('crypto-browserify'),
stream: require.resolve('stream-browserify'),
buffer: require.resolve('buffer/'),
util: require.resolve('util/'),
assert: require.resolve('assert/')
}
}
}
}
};
package.json 스크립트 부분을 다음과 같이 변경했습니다:
jsonCopy"scripts": {
"start": "craco start",
"build": "craco …
```
=> [FE][FIX] Webpack 5 호환성을 위한 crypto 모듈 폴리필 추가

.github/workflows/main.yml, frontend/package.json
이 PR은 CI/CD 파이프라인에서 발생하는 두 가지 주요 문제를 해결합니다:
1. webpack 5에서 Node.js 코어 모듈에 대한 폴리필이 더 이상 자동으로 제공되지 않아 발생하는 `Can't resolve 'crypto'` 오류
2. GitHub Actions 환경에서 craco 실행 파일을 찾지 못해 발생하는 `npm error could not determine executable to run` 오류
이러한 문제들로 인해 프론트엔드 빌드가 실패하고 배포 파이프라인이 중단되고 있었습니다.
- craco.config.js 파일에 webpack 폴리필 설정 추가
- Node.js 코어 모듈(crypto, stream, buffer, util, assert)에 대한 폴리필 구성
```javascript
module.exports = {
webpack: {
configure: {
resolve: {
fallback: {
crypto: require.resolve('crypto-browserify'),
stream: require.resolve('stream-browserify'),
buffer: require.resolve('buffer/'),
util: require.resolve('util/'),
assert: require.resolve('assert/')
}
}
}
}
};
```
빌드 스크립트를 npx를 통해 craco를 직접 실행하는 방식으로 변경:
```json
"scripts": {
"start": "react-scripts start",
"build": "npx craco build", …
```
=> [FIX] CI/CD 빌드 오류

.github/workflows/main.yml, frontend/craco.config.js, frontend/package.json
main.yml 파일에서의 수정사항:
craco.config.js 생성 부분에서 fall***를 fallback으로 수정했습니다.
Node.js 버전을 22에서 더 안정적인 20 LTS 버전으로 변경했습니다.
package.json 파일에서의 수정사항:
빌드 스크립트를 npx craco build에서 craco build로 변경했습니다.
필요한 폴리필 패키지들을 devDependencies에 추가했습니다:
assert
buffer
stream-browserify
util
craco.config.js 파일:
이 파일을 미리 프로젝트에 추가해 GitHub Actions에서 생성하는 대신 이미 존재하게 할 수 있습니다.
webpack 설정에서 fallback 옵션을 올바르게 지정하여 브라우저 환경에서 Node.js 모듈을 사용할 수 있도록 합니다.
=> #389 fix: CI/CD 배포 오류 해결을 위한 빌드 스크립트 수정 2

.github/workflows/main.yml, frontend/README.md
-  CI 빌드 환경에서 devDependencies도 설치하도록 NODE_ENV를 제거하거나 npm install --production=false(또는 --include=dev)를 사용
- 또는 빌드 시 필요한 라이브러리를 dependencies로 옮겨 devDependencies 없이도 빌드가 가능하도록 조정
=> #389 fix: CI/CD 배포 픽스

frontend/src/components/Banner/MainBanner/MainBanner.tsx, frontend/src/components/Banner/VideoBanner/VideoSlide.tsx, frontend/src/components/Header/HeaderStyle.ts, frontend/src/components/Header/Logo/LogoStyle.ts, frontend/src/components/Header/Navigation/NavItemStyle.ts, frontend/src/pages/Main/MainStyle.ts, frontend/src/styles/Container.tsx
- Header 폰트 크기 및 넓이 조정
- Sector 좌우 여백 제거 및 확장
- 메인페이지의 공지사항 및 세미나 컴포넌트 좌우 크기 변경
- 메인 Banner text-transform 속성 제거, 대문자 표시되도록 변경
- 메인페이지 스크린샷, 헤더 폰트 및 하단 Sector 부분 넓이가 커진 것 확인 가능
- @media 속성을 이용하여, 모바일(768px) 및 태블릿(1024px)에 대한 분기 처리를 하였지만 스타일이 깨지는지에 대한 세부적인 피드백 필요
Closes #{409}
=> [FE] [FEAT] 메인페이지 스타일 수정

frontend/src/components/Header/HeaderStyle.ts, frontend/src/components/Header/Logo/LogoStyle.ts, frontend/src/components/Header/Navigation/NavItemStyle.ts
- Header font-weight 100씩 줄임
- HeaderInner padding 삭제, 좌우 여백 줄임 
- 변경된 헤더 스크린샷
- 요구사항 맞게 반영되었는지 확인 필요
=> [FE] [FEAT] 메인페이지 스타일 재수정

backend/src/main/java/org/example/backend/reservation/repository/ReservationRepository.java, backend/src/main/java/org/example/backend/reservation/service/ReservationService.java, backend/src/main/java/org/example/backend/room/repository/RoomRepository.java
- **분산 환경**에서 유용하게 사용할 수 있다는 장점이 있지만, 현재 서비스 규모·요건 상 **Redis 도입으로 얻을 이점**이 크지 않다고 판단했습니다.  
- Redis 인프라를 추가로 운영해야 하므로, **불필요한 리소스·자원 낭비**라고 생각해서 폐기했습니다.
- 낙관적 락은 **충돌 발생 시 재시도 로직**이 필요한데 1인1예약인 상황에선 재시도 로직이 필요 없어보임  
- 사용자 경험 측면에서, 재시도가 발생하면 다시 예약을 시도하세요보다는 그냥 이미 예약됨이 나아보엿습니다.
- **단 하나의 회의실**에 **동일 시간대는 반드시 한 명만 예약**하도록 강제해야 합니다.  
- 성능보다 **중복 예약 방지**가 절대적으로 중요한 요구사항이라고 생각햇습니다.
- 동시에 여러 사용자가 예약을 시도하더라도, 락을 통해 **중복을 원천적으로 막아** 사용자 경험상 **재시도 로직**을 최소화하고자 합니다.
- 성능 저하가 일부 발생하더라도, **중복 방지**가 최우선이므로 비관적 락을 최종 선택했습니다.
@Lock(LockModeType.PESSIMISTIC_WRITE)를 사용하면, JPA는 해당 쿼리를 실행할 때 MySQL의 경우 SELECT … FOR UPDATE와 유사한 방식으로 동작하게 만들 수 있고, 지정된 행에 쓰기 잠금을 획득합니다. 잠금 효과를 제대로 적용시키기 위해 createReservation 메서드를 @Transactional처리 해주어 해당 메서드가 트랜잭션 내에서 실행되게 만들었습니다.
---
**결론**: Redis 락은 서비스 규모 상 과도한 자원 낭비로 보고 …
=> [BE] 예약 서비스 동시성 문제 해결을 위한 비관적 락 적용

backend/src/main/java/org/example/backend/common/aop/logging/LoggingAspect.java, backend/src/main/java/org/example/backend/reservation/repository/ReservationRepository.java
- 일반적으로 @RestController 혹은 @Controller에서 반환된 객체는 스프링이 제공하는 MappingJackson2HttpMessageConverter(내부적으로 ObjectMapper 사용)를 통해 JSON으로 변환됩니다.
- 스프링 부트를 쓰고 있고 com.fasterxml.jackson.datatype:jackson-datatype-jsr310 라이브러리를 의존성에 추가했다면, 스프링 부트의 자동설정(autoconfiguration)이 ObjectMapper에 JavaTimeModule 등을 자동으로 등록해 줍니다.
- 따라서 LocalDateTime 같은 Java 8 날짜/시간 타입이 별도의 설정 없이도 정상적으로 직렬화/역직렬화가 가능한 겁니다.
- 반면, 질문 코드에서 보면 AOP 클래스(LoggingAspect) 내부에 new ObjectMapper()를 통해 새로운 ObjectMapper 인스턴스를 생성하고 있습니다.
- 이렇게 따로 만든 ObjectMapper는 스프링이 자동 등록해준 모듈(예: JavaTimeModule)이 빠진 상태이므로, LocalDateTime을 직렬화하려고 하면 에러가 납니다.
- 그래서 “GET으로 조회할 때는 전혀 문제 없다가, 로깅할 때만 LocalDateTime 직렬화 오류”가 발생했습니다.
따라서 MappingJackson2HttpMessageConverter 처럼 JavaTimeModule을 따로 등록해주어 역직렬화를 해줬습니다.
```java
private final ObjectMapper objectMapper = new …
```
=> ObjectMapper 생성 시 역직렬화 모듈 등록

frontend/src/components/Header/HeaderStyle.ts, frontend/src/components/Header/Logo/LogoStyle.ts, frontend/src/components/Header/Navigation/NavItemStyle.ts, frontend/src/components/Header/TopHeader.tsx, frontend/src/index.css
- TopHeader Padding 제거
- Header 폰트 크기 0.2 줄여 크기 조정
- HeaderInner 좌우 여백 조정 
- TopHeader 링크 조정
- prettier 규칙에 맞게 npx prettier --write . 로 파일들 재정렬
- 노트북 해상도 기준 Header 스크린샷
Closes #409
=> [FE] [FEAT] 헤더 폰트 크기 및 여백 수정 

frontend/package.json, frontend/src/components/NewsSlider/NewsSlider.tsx, frontend/src/components/NewsSlider/NewsSliderStyle.ts, frontend/src/components/layout/AppLayout.tsx, frontend/src/pages/Main/Main.tsx, frontend/src/pages/Main/MainStyle.ts, frontend/src/pages/Main/components/ButtonListSection/ButtonListSection.tsx, frontend/src/pages/Main/components/ButtonListSection/ButtonListSectionStyle.ts, frontend/src/pages/Main/components/ButtonListSection/data.ts, frontend/src/pages/Main/components/VerticalButtonSection/VerticalButtonSection.tsx, frontend/src/pages/Main/components/VerticalButtonSection/VerticalButtonSectionStyle.ts, frontend/src/pages/Main/components/VerticalButtonSection/data.ts, frontend/src/styles/theme.ts
- 메인 Banner 하단 버튼 리스트 컴포넌트 구현
- 메인페이지 공지사항 스타일 일부 변경
- 공지사항 우측 버튼 리스트 구현
- 변경된 메인 페이지 스크린샷
- 더미 데이터들로 API 연결 필요
- react icons 라이브러리 설치, pull 받을시 npm install 필요
=> [FE] [FEAT] 메인페이지 변경된 컴포넌트 구현

backend/src/main/java/org/example/backend/board/controller/BoardController.java, backend/src/main/java/org/example/backend/board/service/BoardService.java, backend/src/main/java/org/example/backend/news/controller/NewsController.java, backend/src/main/java/org/example/backend/news/repository/NewsRepository.java, backend/src/main/java/org/example/backend/news/service/NewsService.java
기존에는 다음과 같은 방식으로 조회수 증가 로직을 구현했었는데요...
Controller 레벨에서 HttpServletRequest, HttpServletResponse를 파라미터로 받아옴
Service 계층에 이들을 그대로 전달 (boardService.incrementViewCount(boardId, request, response))
Service 내부에서:
request.getCookies()로 쿠키를 읽고
쿠키가 없거나, [boardId]가 포함되어 있지 않으면 DB에서 해당 boardId의 조회수를 증가
response.addCookie(...)로 쿠키를 갱신
근데 이렇게 하면 응답 스트림(getWriter() vs getOutputStream()) 충돌이 발생햇습니다..
또 AOP나 필터, 예외 처리 등에서 응답을 한 번 write하거나 flush하면,
이후에 또 다른 로직에서 응답을 생성하려고 할 때 IllegalStateException: getWriter() has already been called for this response 에러가 발생하는 문제를 해결하고자  @CookieValue로 해결했습니다
또한, HttpServletRequest / HttpServletResponse를 Service 계층까지 끌고 가면
테스트가 어려워지고 스프링 Servlet API에 과도하게 의존하게 되서 왠만하면 안쓰는걸 추천드릴게요ㅎㅎ;
Closes #423
=> [BE] getwriter() has already been called for this response 해결 & 뉴스 조회수 로직 추가

frontend/src/pages/Main/components/ButtonListSection/ButtonListSection.tsx, frontend/src/pages/Main/components/ButtonListSection/ButtonListSectionStyle.ts, frontend/src/pages/Main/components/ButtonListSection/data.ts, frontend/src/pages/Main/components/VerticalButtonSection/data.ts
- 메인페이지 링크 정정
- 세미나 클릭시 페이지 이동 구현
- 세미나 버튼 효과 및 페이지 이동 구현
=> [FE] [FEAT] 메인페이지 세미나 버튼 페이지 이동 구현

frontend/src/components/Footer/Footer.tsx, frontend/src/pages/Main/components/ButtonListSection/ButtonListSection.tsx, frontend/src/pages/Main/components/ButtonListSection/ButtonListSectionStyle.ts, frontend/src/pages/Seminar/SeminarCreate.tsx, frontend/src/pages/Seminar/SeminarDetail.tsx, frontend/src/pages/Seminar/SeminarEdit.tsx, frontend/src/pages/Seminar/SeminarList.tsx
- 발표자 -> 연사로 표현 정정
- 메인페이지 세미나 부분 텍스트 순서 조정
- Footer 삭제 및 순서 정정
* 메인페이지 세미나 수정
* Footer 수정
* 발표자 -> 연사로 텍스트 수정
- 모니터 크기에 따른 메인페이지 깨짐 현상은 정상으로 보여 아직 확인 못함
Closes #440
=> [FE] [FEAT] 일부 텍스트 및 디자인 수정
