- frontend/.eslintrc.json
- frontend/.prettierrc
- eslint가 타입스크립트를 제대로 파싱하도록 설정
- 운영체제 간 다른 줄바꿈 차이 문제 해결
Closes #6
> fix: 오류 수정

- backend/build.gradle
- backend/src/main/java/org/example/backend/controller/ProfessorController.java
- backend/src/main/java/org/example/backend/domain/dto/ResponseDto.java
- backend/src/main/java/org/example/backend/domain/dto/professor/CreateProfessorDto.java
- backend/src/main/java/org/example/backend/domain/dto/professor/ProfessorReqDto.java
- backend/src/main/java/org/example/backend/domain/dto/professor/ProfessorResDto.java
- backend/src/main/java/org/example/backend/domain/entity/Professor.java
- backend/src/main/java/org/example/backend/domain/mapper/ProfessorMapper.java
- backend/src/main/java/org/example/backend/repository/ProfessorRepository.java
- backend/src/main/java/org/example/backend/service/ProfessorService.java
- 교수 엔티티
- CRUD
- swagger, mapper 의존성 추가
아직 department 와 테이블 매핑 미진행
Closes #10
> [BE] Feature/10: Professor 엔티티 및 기본적 CRUD 설계

- .idea/vcs.xml
- .idea/workspace.xml
- backend/src/main/java/org/example/backend/controller/DepartmentController.java
- backend/src/main/java/org/example/backend/domain/dto/Department/DepartmentDto.java
- backend/src/main/java/org/example/backend/domain/entity/Department.java
- backend/src/main/java/org/example/backend/repository/DepartmentRepository.java
- backend/src/main/java/org/example/backend/service/DepartmentService.java
Department Entity, CRUD
Closes #12
> [BE] Department 엔티티 및 CRUD

- backend/src/main/java/org/example/backend/department/controller/DepartmentController.java
- backend/src/main/java/org/example/backend/department/domain/dto/Department/DepartmentDto.java
- backend/src/main/java/org/example/backend/department/domain/entity/Department.java
- backend/src/main/java/org/example/backend/department/domain/mapper/DepartmentMapper.java
- backend/src/main/java/org/example/backend/department/repository/DepartmentRepository.java
- backend/src/main/java/org/example/backend/department/service/DepartmentService.java
- backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
- backend/src/main/java/org/example/backend/professor/domain/dto/ResponseDto.java
- backend/src/main/java/org/example/backend/professor/domain/dto/professor/ProfessorReqDto.java
- backend/src/main/java/org/example/backend/professor/domain/dto/professor/ProfessorResDto.java
- backend/src/main/java/org/example/backend/professor/domain/entity/Professor.java
- backend/src/main/java/org/example/backend/professor/domain/mapper/ProfessorMapper.java
- backend/src/main/java/org/example/backend/professor/repository/ProfessorRepository.java
- backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
> [BE] refactor: 디렉토리 구조 변경

- frontend/src/App.tsx
- frontend/src/components/Modal/Modal.tsx
- frontend/src/components/Modal/useModal.tsx
- frontend/src/pages/Auth/SignIn.tsx
- frontend/src/styles/ModalStyle.ts
<br/>
모달 만들고 App.tsx에서 모달 불러와서 테스트했어요. 테스트 후 App.tsx에 있는 모달은 없앴고, 추후에 필요한 페이지에서 모달 불러와서 쓰시면 됩니다.
저는 모달을 필요한 페이지에서만 만들고 재사용해본 적이 없어서 공부 겸, 기억할 겸 밑에 모달 사용법도 적어봤어요! 
모달 구현
https://github.com/user-attachments/assets/befcb43b-4210-49dc-bcbc-32acd88425a6
1. 필요한 파일 import
```javascript
import Modal from './(경로)/Modal';
import useModal from './(경로)/useModal';
```
<br/>
2. 커스텀 훅 선언
```javascript
const { isModalOpen, openModal, closeModal } = useModal();
```
<br/>
3. 모달 사용
(예시)
```javascript
<button onClick={openModal}>모달 버튼</button>
<Modal isOpen={isModalOpen} onClose={closeModal}>
모달 내용
</Modal>
```
<br/>
Closes #33
> [FE] 모달 구현

- backend/src/main/java/org/example/backend/global/config/CorsMvcConfig.java
- backend/src/main/java/org/example/backend/global/config/SecurityConfig.java
Cors 기능 추가
3000포트 적용
Closes #53
> feat: Cors 기능 추가

- backend/build.gradle
- backend/src/main/java/org/example/backend/global/config/SecurityConfig.java
- backend/src/main/java/org/example/backend/global/config/SwaggerConfig.java
- backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
swagger 연결
http://localhost:8080/swagger-ui/index.html#/
아직 예제 작성은 안함
Closes #32
> [BE] swagger 기본 설정

- backend/.gitignore
- backend/build.gradle
- backend/src/main/java/org/example/backend/department/domain/mapper/DepartmentMapper.java
- backend/src/main/java/org/example/backend/department/service/DepartmentService.java
- backend/src/main/java/org/example/backend/professor/domain/mapper/ProfessorMapper.java
- backend/src/main/resources/application.properties
- backend/src/test/java/org/example/backend/department/controller/DepartmentControllerTest.java
- backend/src/test/java/org/example/backend/department/repository/DepartmentRepositoryTest.java
- backend/src/test/java/org/example/backend/department/service/DepartmentServiceTest.java
restassured vs mockmvc을 고민하다가 추후 인증로직을 생각하면 어려울것같아서 mockmvc를 도입했습니다.
https://velog.io/@iseon_u/MockMvc-Rest-Assured-%EC%B0%A8%EC%9D%B4
controller측에서 인증로직에 걸려서 아직 제대로 작동하지 않음. 로그인 기능 병합 후 검사 필요.
Closes #28
> [BE] test: 부서 테스트 코드 작성

- frontend/.dockerignore
- frontend/Dockerfile
- frontend/package.json
---
- [Docker Desktop 다운로드](https://www.docker.com/products/docker-desktop)
---
터미널에서 프로젝트 루트 디렉토리로 이동
```bash
cd frontend
```
---
Dockerfile을 기준으로 이미지를 빌드 이 명령어는 `dibb-frontend`라는 이름으로 이미지를 생성
```bash
docker build -t dibb-frontend .
```
빌드가 완료되면 Docker 이미지를 확인할 수 있음
```bash
docker images
```
---
이미지를 실행하기 위해 아래 명령어를 입력 컨테이너의 포트 3000을 호스트 머신의 포트 3000에 매핑하여 브라우저에서 애플리케이션에 접근 가능하도록 설정
```bash
docker run -p 3000:3000 dibb-frontend
```
이후 브라우저에서 `http://localhost:3000`에 접속하여 애플리케이션을 확인
---
로컬에서 코드를 수정할 때마다 Docker 컨테이너를 다시 빌드하지 않고 실시간으로 반영되게 하려면 `-v` 옵션을 사용하여 로컬 디렉토리를 컨테이너에 마운트
```bash
docker run -p 3000:3000 -v $(pwd):/usr/src/app dibb-frontend
```
이 명령어는 로컬에서 파일을 수정할 때 Docker 컨테이너에서도 즉시 반영되도록 설정
---
컨테이너 실행 후 종료하려면 터미널에서 `Ctrl + C`를 입력 백그라운드에서 실행 중인 컨테이너를 강제로 종료하려면 아래 명령어를 사용
```bash
docker …
```
> #47 [FE] Dockerfile 구성

- frontend/src/context/AuthContext.tsx
- frontend/src/pages/Auth/SignIn.tsx
로그인 시 이메일에서 아이디 사용으로 변경
Closes #58
> #58 refactor: 로그인 이메일에서 아이디 형식으로 변경

- backend/Dockerfile
> [BE] 도커 파일 생성

- backend/.gitignore
- backend/src/main/java/org/example/backend/admin/domain/entity/Admin.java
Closes #63
터미널에서 프로젝트 루트 디렉토리로 이동
```bash
cd backend
```
---
Docker 이미지란?
- 컨테이너를 실행하기 위한 템플릿
- 애플리케이션의 코드, 런타임, 라이브러리 등이 포함된 불변의 파일 시스템 스냅샷
- 컨테이너는 이 이미지를 기반으로 실행
- ex) Spring 애플리케이션을 실행하기 위한 Spring과 그 애플리케이션 코드가 들어간 이미지
</br>
`dibb-backend`라는 이름으로 이미지 생성
```bash
docker build -t dibb-backend .
```
</br>
</br>
빌드가 완성되면 Docker 이미지를 확인할 수 있음
```bash
docker images
```
---
이미지를 실행하기 위해 컨테이너 실행
</br> 
- 컨테이너 이름: `dibb-backend-container-stable`
- 이미지 이름: `dibb-backend`
- 태그: `lastest`
- 호스트 포트: `8081`
</br>
백그라운드 재생
``` bash
docker run -d --name dibb-backend-container-stable -p 8081:8080 dibb-backend:latest
```
- 컨테이너 이름: `dibb-backend-container-dev`
- 이미지 이름: `dibb-backend`
- 태그: `dev`
- 호스트 포트: `8082`
</br>
실시간 코드 반영
``` bash
docker run -p 8082:8080 -v $(pwd)/build/libs:/app --name …
```
> [BE] 도커 db 연결

- backend/backup.sql
db 데이터 backup 파일 설정
실행되고 있는 dev 컨테이너를 중지하고, 데이터 볼륨과 이미지를 키운 후 다시 실행
``` bash
docker-compose -f docker-compose-dev.yml down -v
docker-compose -f docker-compose-dev.yml up --build
```
테이블이 자동 생성되고 데이터도 들어가있음
Closes #63
> [BE] 더미 데이터 넣은 backup 파일

- backend/src/main/java/org/example/backend/admin/domain/dto/AdminResDto.java
- backend/src/main/java/org/example/backend/admin/domain/dto/SignInReqDto.java
- backend/src/main/java/org/example/backend/admin/domain/dto/SignInResDto.java
- backend/src/main/java/org/example/backend/admin/repository/AdminRepository.java
- backend/src/main/java/org/example/backend/admin/service/AdminService.java
- backend/src/main/java/org/example/backend/admin/service/CustomUserDetailsService.java
- backend/src/main/java/org/example/backend/global/config/CustomAuthenticationFailureHandler.java
- backend/src/main/java/org/example/backend/global/config/SecurityConfig.java
- backend/src/main/java/org/example/backend/global/config/SwaggerConfig.java
- backend/src/main/java/org/example/backend/jwt/JWTFilter.java
- backend/src/main/java/org/example/backend/jwt/JWTUtil.java
- backend/src/main/java/org/example/backend/jwt/LoginFilter.java
- swagger 로그인 api 추가
- login api가 따로 존재하지 않아 swagger 설정 파일에 추가
Closes #70
> [BE] swagger 로그인 api 추가

- backend/src/main/java/org/example/backend/admin/domain/dto/AdminResDto.java
- backend/src/main/java/org/example/backend/admin/domain/dto/SignInReqDto.java
- backend/src/main/java/org/example/backend/admin/domain/dto/SignInResDto.java
- backend/src/main/java/org/example/backend/admin/repository/AdminRepository.java
- backend/src/main/java/org/example/backend/admin/service/AdminService.java
- backend/src/main/java/org/example/backend/admin/service/CustomUserDetailsService.java
- backend/src/main/java/org/example/backend/global/config/CustomAuthenticationFailureHandler.java
- backend/src/main/java/org/example/backend/global/config/SecurityConfig.java
- backend/src/main/java/org/example/backend/jwt/JWTFilter.java
- backend/src/main/java/org/example/backend/jwt/JWTUtil.java
- backend/src/main/java/org/example/backend/jwt/LoginFilter.java
1. login 실패 시 에러 메세지 추가
2. jwt 버그 리뷰 수정 사항
- 불필요한 어노테이션 삭제
4. 로그인 필드 수정: username, password -> loginId, password
- 기본 SpringSecurity 로그인 필드가 username과 password
- 이를 커스터마이징하여 username -> loginId로 수정
- username은 화면 상 "관리자"로 표시될 필드로 예상 중
^ 작업 1. login 실패 시 에러 메시지 test
</br>
^ 작업 2. 로그인 필드 수정 후 기능 test
오류 중앙화 작업은 추후 수정
@pillow12360
로그인 기능에서 username을 loginId로 바꾸는 게 프론트엔드에서 괜찮을 지 알려주세요~
만약 어려우시면 기존 로그인 방식은 그대로 두고 loginId 필드를 수정하겠습니다
Closes #62
> [BE] 로그인 기능 점검

- frontend/src/context/AuthContext.tsx
- frontend/src/pages/Auth/SignIn.tsx
> [FE] refact: 명세 기반으로 로직 수정

- frontend/public/horizontalBar.svg
- frontend/src/App.tsx
- frontend/src/components/Footer/Footer.tsx
- frontend/src/pages/About/Faculty.tsx
- frontend/src/pages/About/FacultyStyle.ts
- frontend/src/pages/Undergraduate/styles/UndergraduateStyle.tsx
교수 소개 페이지 구현 (하드코딩)
서버 연결 필요
Closes #51
> [FE] 교수 소개 페이지 구현

- backend/src/test/java/org/example/backend/department/controller/DepartmentControllerTest.java
- backend/src/test/java/org/example/backend/department/service/DepartmentServiceTest.java
빌드 에러 수정
추후 통합테스트로 변경
Closes #81
> #81 fix: 부서테스트빌드에러 수정

- backend/.env.example
- backend/.gitignore
- backend/Dockerfile
- backend/docker-compose-stable.yml
- backend/src/main/java/org/example/backend/global/config/SwaggerConfig.java
- backend/src/test/java/org/example/backend/department/repository/DepartmentRepositoryTest.java
- backend/src/test/java/org/example/backend/department/service/DepartmentServiceTest.java
- backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
- 설정 파일 수정
---
(stable 을 기준으로 한 설명 + 컨테이너는 이미 만들어져 있음을 가정)
``` bash
docker network inspect stable-network
```
-> 네트워크가 존재하지 않음
---
``` bash
docker network create stable-network
```
</br>
다시 네트워크 확인
- 네트워크 생성 됨
---
``` bash
docker-compose -f docker-compose-stable.yml build --no-cache
```
---
``` bash
docker-compose -f docker-compose-stable.yml up    
```
---
<br>
(dev 성공 스크린샷)
- @urinaner dev에 맞는 명령어로 수정하면 됩니다
---
개인 환경에서 테스트 후 확인 부탁드립니다~
Closes #78
> [BE] docker 연결 수정 사항

- backend/src/main/java/org/example/backend/board/domain/entity/Board.java
- backend/src/main/java/org/example/backend/seminar/domain/entity/Seminar.java
- backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
게시판, 세미나, 논문 엔티티 설계
예약 시스템 제외
Closes #71
> [BE] feat : 나머지 엔티티 설계

- backend/src/main/resources/data.sql
더미데이터 추가
```
sql:
init:
mode: always
```
요 세팅을 yml에 안넣어주면 안들어간다. (겨우찾음)
Closes #93
> chore: 더미데이터 추가

- frontend/src/App.tsx
- frontend/src/AppContent.tsx
- frontend/src/components/Footer/Footer.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Header/NavItem.tsx
- frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
- frontend/src/pages/News/NoticeBoard/NoticeBoardStyle.ts
- frontend/src/styles/HeaderStyles.ts
- 데스크톱/모바일 전환 시 레이아웃 최적화
- 가로 스크롤 지원
- 모바일에서의 메뉴 접근성 향상
```typescript
// 디바이스별 동작 분리
const handleNavItemMouseEnter = (index: number) => {
if (!isMobile) setActiveIndex(index);
};
const handleNavItemClick = (index: number) => {
if (isMobile) setActiveIndex(activeIndex === index ? null : index);
};
```
```typescript
<Header>
<NavItem 
title="메뉴명"
path="/path"
onMouseEnter={handleMouseEnter}
onClick={handleClick}
/>
</Header>
```
```typescript
const [isMobile, setIsMobile] = useState(window.innerWidth <= 768);
useEffect(() => {
const handleResize = () => setIsMobile(window.innerWidth <= 768);
window.addEventListener('resize', handleResize);
return () => window.removeEventListener('resize', handleResize);
}, []);
```
```typescript
const [activeIndex, setActiveIndex] = useState<number | …
```
> [FE] 헤더 레이아웃 반응형 로직 개선

- backend/src/main/java/org/example/backend/board/controller/BoardController.java
- backend/src/main/java/org/example/backend/board/service/BoardService.java
- backend/src/main/java/org/example/backend/professor/domain/dto/ResponseDto.java
> [BE] 보드 페이징

- frontend/src/pages/Main/Main.tsx
메인 페이지의 바로가기 링크 모음에서 교내양식 링크 수정
Closes #99
> [FE] 메인 페이지 바로가기 링크 수정

- backend/docker-compose-dev.yml
- backend/src/main/resources/data.sql
- backend/src/main/resources/schema.sql
더미데이터 data.sql  docker-compose 연결
테스트 필요
> feat(docker-compose): 더미 데이터 경로 설정

- backend/docker-compose-dev.yml
- backend/src/main/generated/org/example/backend/admin/domain/mapper/SignInMapperImpl.java
- backend/src/main/generated/org/example/backend/board/domain/mapper/BoardMapperImpl.java
- backend/src/main/generated/org/example/backend/department/domain/mapper/DepartmentMapperImpl.java
- backend/src/main/generated/org/example/backend/professor/domain/mapper/ProfessorMapperImpl.java
- backend/src/main/generated/org/example/backend/seminar/domain/mapper/SeminarMapperImpl.java
- backend/src/main/generated/org/example/backend/thesis/domain/mapper/ThesisMapperImpl.java
- backend/src/main/java/org/example/backend/board/controller/BoardController.java
- backend/src/main/java/org/example/backend/board/domain/dto/BoardReqDto.java
- backend/src/main/java/org/example/backend/department/controller/DepartmentController.java
- backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
- backend/src/main/java/org/example/backend/seminar/controller/SeminarController.java
- backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/data.sql
> [Bug] swagger 상세정보란 수정

- frontend/src/context/ModalStyle.ts
- z-index를 수정해 모달이 다른 컴포넌트보다 앞으로 오게 함
Closes #109
> [FE] 모달 렌더링 버그

- frontend/.env.development
- frontend/package-lock.json
- frontend/package.json
- frontend/src/AppContent.tsx
- frontend/src/config/apiConfig.ts
- frontend/src/context/AuthContext.tsx
- frontend/src/global.d.ts
- frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
- frontend/src/pages/News/NoticeBoard/NoticeBoardStyle.ts
- frontend/src/pages/News/NoticeBoard/NoticeCreate.tsx
- frontend/src/pages/News/NoticeBoard/NoticeCreateStyle.ts
- frontend/src/pages/News/NoticeBoard/NoticeDetail.tsx
- frontend/src/pages/News/NoticeBoard/NoticeDetailStyle.ts
- frontend/src/react-quill.d.ts
- frontend/src/types/board.ts
- 게시글 작성, 조회 기능 테스트 완료 - 배포된 api 기준 정상 작동
- ReactQuill 에디터 통합
- 파일 업로드 UI/UX 구현
- 카테고리 선택 기능 추가
- 학부/대학원/취업/장학 카테고리 구분
- 폼 유효성 검사 구현
- 에러 핸들링 및 사용자 피드백
- Quill 에디터 콘텐츠 렌더링
- DOMPurify를 통한 XSS 방지
- 메타 정보 표시 (작성자, 작성일, 조회수, 카테고리)
- 파일 다운로드 UI 구현
- 반응형 디자인 적용
- Styled-components를 활용한 컴포넌트 스타일링
- 반응형 디자인 구현
- 일관된 UI/UX 제공
1. 백엔드
- 카테고리 필터링 파라미터 동작 안함 (항상 전체)
2. 서식 지정 시 500 에러 발생
- 추후 검토 필요
1. 파일 업로드 기능
- 현재는 파일명만 전송
- 실제 파일 업로드 기능 구현 필요
2. 서식 에러 처리
3. 게시글 수정 및 삭제 처리 로직 구현
Closes#107
> [FE] 바용소식 - 공지사항 리스트 조회, 게시글 작성, 상세 페이지 기능 구현

- backend/build.gradle
- backend/src/main/generated/org/example/backend/admin/domain/mapper/SignInMapperImpl.java
- backend/src/main/generated/org/example/backend/board/domain/mapper/BoardMapperImpl.java
- backend/src/main/generated/org/example/backend/department/domain/mapper/DepartmentMapperImpl.java
- backend/src/main/generated/org/example/backend/professor/domain/mapper/ProfessorMapperImpl.java
- backend/src/main/generated/org/example/backend/seminar/domain/mapper/SeminarMapperImpl.java
- backend/src/main/generated/org/example/backend/thesis/domain/mapper/ThesisMapperImpl.java
- backend/src/main/java/org/example/backend/admin/domain/entity/Admin.java
- backend/src/main/java/org/example/backend/common/exception/ExceptionControllerAdvice.java
- backend/src/main/java/org/example/backend/department/controller/DepartmentController.java
- backend/src/main/java/org/example/backend/department/domain/entity/Department.java
- backend/src/main/java/org/example/backend/department/service/DepartmentService.java
- backend/src/main/java/org/example/backend/global/config/SecurityConfig.java
- backend/src/main/java/org/example/backend/global/config/SjConfig.java
- backend/src/main/java/org/example/backend/professor/domain/entity/Professor.java
- backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
- backend/src/main/java/org/example/backend/thesis/domain/entity/Thesis.java
- backend/src/main/java/org/example/backend/user/controller/UserController.java
- backend/src/main/java/org/example/backend/user/service/UserService.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/data.sql
- backend/src/test/java/org/example/backend/SjTest.java
- backend/src/test/java/org/example/backend/department/controller/DepartmentControllerTest.java
- backend/src/test/java/org/example/backend/department/repository/DepartmentRepositoryTest.java
- backend/src/test/java/org/example/backend/professor/domain/mapper/ProfessorMapperTest.java
- backend/src/test/java/org/example/backend/professor/repository/ProfessorRepositoryTest.java
- backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
1. 교수 삭제 메서드에 transactional 어노테이션 추가
2. 부서 포멧 수정
- controller url format: departments -> department
- entity: departmentId -> id
- table명 추가
- path 파라미터 명시적 확인
cascade 좀 더 논의 필요 -> 추가적인 이슈 등록
@pillow12360 merge 되면 API 명세서 부서 URL 수정해놓겠습니다~
Closes #127
> [BE] 기본 CRUD 수정사항 점검

- backend/src/main/generated/org/example/backend/admin/domain/mapper/SignInMapperImpl.java
- backend/src/main/generated/org/example/backend/board/domain/mapper/BoardMapperImpl.java
- backend/src/main/generated/org/example/backend/department/domain/mapper/DepartmentMapperImpl.java
- backend/src/main/generated/org/example/backend/professor/domain/mapper/ProfessorMapperImpl.java
- backend/src/main/generated/org/example/backend/seminar/domain/mapper/SeminarMapperImpl.java
- backend/src/main/generated/org/example/backend/thesis/domain/mapper/ThesisMapperImpl.java
- backend/src/main/java/org/example/backend/department/domain/mapper/DepartmentMapper.java
> fix: 부서 mapper departemntId 수정

- backend/src/main/java/org/example/backend/board/controller/BoardController.java
- backend/src/main/java/org/example/backend/board/domain/entity/Category.java
- backend/src/main/java/org/example/backend/board/repository/BoardRepository.java
- backend/src/main/java/org/example/backend/board/service/BoardService.java
---
- **카테고리 기능 추가**: 기존의 `/api/board` 경로를 확장하여 카테고리별 게시물 조회 기능을 추가.
- **주소 분리**: 기능이 몰려있다고 판단해 분리.
1. **전체 게시물 조회**
- **Endpoint**: `GET /api/board`
- **Query Parameters**:
- `page`: 페이지 번호 (기본값: 0)
- `size`: 페이지 크기 (기본값: 2)
- **요청 예시**: 
```
/api/board?page=0&size=2
```
2. **카테고리별 게시물 조회**
- **Endpoint**: `GET /api/board/category/{카테고리}`
- **Path Parameters**:
- `{카테고리}`: 카테고리 이름 (예: employment, graduate, undergraduate, scholarship)
- **Query Parameters**:
- `page`: 페이지 번호 (기본값: 0)
- `size`: 페이지 크기 (기본값: 2)
- **요청 예시**:
```
/api/board/category/graduate?page=0&size=2
```
@pillow12360 테스트 후 문제없으면 병합부탁~
Closes #129
> [BE] 게시판 필터링 기능 추가

- backend/src/main/generated/org/example/backend/thesis/domain/mapper/ThesisMapperImpl.java
- backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
- backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
- backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
- backend/src/main/java/org/example/backend/thesis/repository/ThesisRepository.java
- backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
논문, 교수별 조회 로직 추가
@urinaner  url 형식이 적절한지 잘 모르겠습니다~ 한번 확인해주세요!!
Closes #138
> [BE] 논문, 교수별 조회 로직 추가

- frontend/src/pages/SeminarRoom/Reservation.tsx
세미나실 캘린더 네비게이션 단위 수정
Closes #141
> [FE] 세미나실 예약 캘린더 네비게이션 수정

- frontend/src/AppContent.tsx
- frontend/src/components/Footer/Footer.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Header/HeaderStyles.ts
- frontend/src/components/ProtectedRoute/ProtectedRoute.tsx
- frontend/src/config/apiConfig.ts
- frontend/src/context/AuthContext.tsx
- frontend/src/hooks/useAuth.tsx
- frontend/src/pages/Auth/AdminSignIn.tsx
관리자 권한 보호 페이지 : Professor(C,U,D) Notice(C,U,D)
1. 인증 컨텍스트 (AuthContext) 코드 수정
2. 보호된 라우트 (ProtectedRoute) 컴포넌트 구현
3. 로그인/로그아웃 기능 구현
4. 관리자/일반 사용자 권한 관리 추가
5. 관리자 로그인 URI 변경 (/signin → /admin/signin)
6. 일반 사용자 로그인 및 관리자 로그인 요청 분리
- 사용자 로그인 상태
- 관리자 권한 상태
- 로딩 및 에러 상태
- Public Routes (모든 사용자 접근 가능)
- Protected Routes (로그인 필요)
- Admin Routes (관리자 권한 필요)
- 미인증 사용자 → 로그인 페이지
- 권한 없는 사용자 → 메인 페이지
- 인증된 사용자의 로그인 페이지 접근 → 메인 페이지
\`\`\`
src/
├── context/
│   └── AuthContext.tsx
├── components/
│   └── ProtectedRoute/
│       └── ProtectedRoute.tsx
├── hooks/
│   └── useAuth.ts
└── AppContent.tsx
\`\`\`
\`\`\`typescript
// 일반 보호 라우트
<Route
path="/protected"
element={
<ProtectedRoute requireAuth>
<ProtectedComponent />
</ProtectedRoute>
}
/>
// 관리자 전용 라우트
<Route
path="/admin"
element={ …
> [FE] [FEAT] 라우트 가드 기능 구현

- backend/src/main/java/org/example/backend/global/config/S3Uploader.java
- backend/src/main/java/org/example/backend/reservation/domain/Reservation.java
- backend/src/main/java/org/example/backend/reservation/domain/ReservationPurpose.java
- backend/src/main/java/org/example/backend/reservation/domain/ReservationStatus.java
- backend/src/main/java/org/example/backend/seminarRoom/domain/SeminarRoom.java
- backend/src/main/java/org/example/backend/user/domain/entity/User.java
User, Reservation, SeminarRoom 엔티티 설계
Closes #154
> [BE] User, Reservation, SeminarRoom 엔티티 설계

- backend/src/main/java/org/example/backend/seminarRoom/domain/SeminarRoom.java
> [BE] 빌드 에러 수정

- backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
- backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
- backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
- backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
- professor.update 메서드 요청 Body 방식 수정
- thesis.update 메서드 요청 Body 방식 수정
노션 링크: https://www.notion.so/update-5202da86dec8425d956779366a3768a3?pvs=4
Closes #170
> [BE] 교수, 논문 update 기능에 파일 형식 추가

- backend/src/main/java/org/example/backend/board/controller/BoardController.java
- backend/src/main/java/org/example/backend/board/service/BoardService.java
- backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
- backend/src/main/java/org/example/backend/professor/service/ProfessorService.java
- backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
- backend/src/main/java/org/example/backend/thesis/service/ThesisService.java
- professor 생성, 수정에서 파일 필드를 필수 필드에서 제외
- board 생성, 수정에서 파일 필드를 필수 필드에서 제외,
- thesis 생성, 수정에서 파일 필드를 필수 필드에서 제외
순서대로 professor, board, thesis 생성
Closes #177
> [BE] [REFACTOR] 파일 필드를 필수 필드에서 제외

- frontend/src/pages/Main/Main.tsx
- frontend/src/pages/Main/MainStyle.ts
- 메인 페이지 논문 부분에 저자 대신 제목 표시
- 제목, 내용 모두 3줄 초과 시 말줄임표(...) 표시
- 일부 반응형 디자인 수정
Closes #199
> [FE] 메인 페이지 논문 부분에 저자 대신 제목 표시

- backend/src/main/java/org/example/backend/board/controller/BoardController.java
- backend/src/main/java/org/example/backend/professor/controller/ProfessorController.java
- backend/src/main/java/org/example/backend/thesis/controller/ThesisController.java
> [BE] refactor: pageDto

- backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java
- backend/src/main/java/org/example/backend/board/domain/entity/Board.java
> [BE] refactor: createDate

- backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java
- 게시글: createDate -> createdDate
Closes #214
> [BE] [REFACTOR] 게시글 생성일 필드 수정

- backend/src/main/java/org/example/backend/seminar/controller/SeminarController.java
- backend/src/main/java/org/example/backend/seminar/service/SeminarService.java
세미나 전체 조회 기능 추가
노션 명세서
https://www.notion.so/CRUD-API-f752625231cc4869a52e1e6d4eb3bf86?pvs=4
Closes #216
> [BE] [FEAT] 세미나 전체 조회 기능 추가

- backend/src/main/java/org/example/backend/reservation/controller/ReservationController.java
- backend/src/test/java/org/example/backend/ControllerTestSupport.java
- backend/src/test/java/org/example/backend/IntegrationTestSupport.java
- backend/src/test/java/org/example/backend/department/service/DepartmentServiceTest.java
- backend/src/test/java/org/example/backend/professor/controller/ProfessorControllerTest.java
- backend/src/test/java/org/example/backend/professor/service/ProfessorServiceTest.java
> fix : 테스트 에러 수정

- frontend/package-lock.json
- frontend/src/components/Footer/FooterStyle.ts
- 배경색상 변경
- 글자색상 흰색으로 변경
- copyright 위 수평선 삭제
- 행간 넓힘 (8px -> 18px)
행간은 넓혀져있음
관리자 로그인 버튼은 임시로 놔둠. 추후 삭제 필요
Closes #222
> [FE] 푸터 수정

- backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java
- backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
> feat : 배포 사이트 cors 추가

- backend/src/main/java/org/example/backend/seminar/domain/dto/SeminarReqDto.java
- backend/src/main/java/org/example/backend/seminar/domain/dto/SeminarResDto.java
- backend/src/main/java/org/example/backend/seminar/domain/entity/Seminar.java
- backend/src/main/java/org/example/backend/seminar/service/SeminarService.java
- backend/src/main/resources/data.sql
- 세미나 삭제 기능 @Transectional 어노테이션 추가
- 세미나 시간 기능 추가
- 필드별 글자 수 제한 추가
명세서 업데이트 사항 : https://www.notion.so/FIX-7cc1ec226c58468ea082074cbeabcb9c?pvs=4
Closes #253
> [BE] [FIX] 세미나 시간 추가 및 삭제기능 수정

- backend/backup.sql
- backend/src/main/resources/data.sql
> fix: 예약 엔티티 필드 수정

- frontend/src/pages/Main/Main.tsx
- frontend/src/pages/Main/MainStyle.ts
> #252 style: 메인페이지 화면 밖 렌더링 수정

- backend/src/main/java/org/example/backend/jwt/LoginFilter.java
accessToken 유효시간 증가 : 100000000 * 1800 * 100 * 10L;
> [BE] [REFACTOR] accessToken 유효시간 증가

- backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
- backend/src/main/java/org/example/backend/global/util/OctetStreamReadMsgConverter.java
application/octet-stream 변환 컨버터 설정
기본 메세지 컨버터 이해 필요.
https://findsilverlining.tistory.com/143
Closes #273
> [BE] fix: application/octet-stream 변환로직 추가

- frontend/package.json
- frontend/public/index.html
- frontend/src/common/Button/Button.tsx
- frontend/src/components/Banner/MainBanner/MainBanner.tsx
- frontend/src/components/Banner/PageBanner/PageBanner.tsx
- frontend/src/components/Banner/VideoBanner/VideoSlide.tsx
- frontend/src/components/Footer/FooterStyle.ts
- frontend/src/components/Header/Logo/LogoStyle.ts
- frontend/src/components/Modal/components/ModalHeader.tsx
- frontend/src/components/Modal/context/ModalContext.tsx
- frontend/src/index.css
- frontend/src/pages/About/AboutStyle.ts
- frontend/src/pages/About/Faculty/FacultyStyle.ts
- frontend/src/pages/About/Faculty/ProfessorDetailStyle.ts
- frontend/src/pages/About/Faculty/ProfessorEditStyle.ts
- frontend/src/pages/About/Faculty/ProfileSectionStyle.ts
- frontend/src/pages/About/Faculty/TabSectionStyle.ts
- frontend/src/pages/About/Faculty/tabs/PublicationsStyle.ts
- frontend/src/pages/Auth/SignInPageStyle.ts
- frontend/src/pages/Graduate/GraduateOverviewStyle.tsx
- frontend/src/pages/Main/Main.tsx
- frontend/src/pages/Main/MainStyle.ts
- frontend/src/pages/News/News/NewsCreateStyle.ts
- frontend/src/pages/News/News/NewsDetailStyle.ts
- frontend/src/pages/News/Thesis/ThesisDetailStyle.ts
- frontend/src/pages/Seminar/SeminarDetail.tsx
- frontend/src/styles/GlobalStyle.ts
- 기본 폰트, 다른 폰트로 적용되어있던 페이지의 폰트를 모두 나눔스퀘어로 변경
- 나눔스퀘어로 변경함에 따라 폰트 굵기 일부 수정
Light(300), Regular(400), Bold(700), Extra Bold(800)가 아닌 글씨는 어색해보일 수 있음
Closes #277
> [FE] 전체 페이지 폰트 변경

- frontend/package.json
> #285 fix: framer 타입오류 해결 다운그레이드

- .github/workflows/main.yml
secrets.SERVER_IP를 secrets.SJ_HOST로 수정했어요.
서버에서 수동으로 배포를 성공했어요.(Nginx는 conf파일 문제가 있어요.)
현재 서버에서 실행되고 있는 도커 이미지들의 태그를 수정했어요.
[작업 내용](https://tidy-animantarx-25b.notion.site/On-Premise-Docker-Docker-Compose-CI-CD-MySQL-17f6d55ac0f0801897aacf71f9498d4e?pvs=4)
Closes #{290}
> [CI/CD]: Docker 이미지 태그 통일

- frontend/src/pages/About/Organization/OrganizationStyle.ts
- frontend/src/pages/Seminar/SeminarDetail.tsx
- frontend/src/pages/Seminar/SeminarList.tsx
모바일 환경에서
- 세미나 목록 페이지 디자인 변경
- 세미나 세부사항 페이지 디자인 일부 수정
- 제목 축소
- 레이아웃 약간 변경
Closes #295
> [FE] 세미나페이지 반응형 디자인 구현

- frontend/src/pages/News/Thesis/ThesisDetailStyle.ts
- frontend/src/pages/News/Thesis/ThesisList.tsx
- frontend/src/pages/News/Thesis/ThesisStyle.ts
- frontend/src/pages/Seminar/SeminarDetail.tsx
- frontend/src/pages/Seminar/SeminarList.tsx
모바일 환경에서
- 연구논문 리스트 페이지 디자인 변경
- 연구논문 세부사항 페이지 디자인 일부 수정
- 제목 축소
- 레이아웃 일부 변경
- 연구논문 리스트(및 세미나 리스트) 페이지에서 등록 버튼의 위치 및 크기 수정
Closes #297
> [FE] 연구논문 조회 페이지 모바일 반응형 디자인 구현

- frontend/public/index.html
- frontend/src/components/Banner/MainBanner/MainBanner.tsx
- frontend/src/components/Banner/PageBanner/PageBanner.tsx
- frontend/src/components/Banner/VideoBanner/VideoSlide.tsx
- frontend/src/components/Footer/FooterStyle.ts
- frontend/src/components/Header/Logo/LogoStyle.ts
- frontend/src/components/Modal/components/ModalHeader.tsx
- frontend/src/components/Modal/context/ModalContext.tsx
- frontend/src/pages/About/AboutStyle.ts
- frontend/src/pages/About/Faculty/FacultyStyle.ts
- frontend/src/pages/About/Faculty/ProfessorDetailStyle.ts
- frontend/src/pages/About/Faculty/ProfessorEditStyle.ts
- frontend/src/pages/About/Faculty/ProfileSectionStyle.ts
- frontend/src/pages/About/Faculty/TabSectionStyle.ts
- frontend/src/pages/About/Faculty/tabs/PublicationsStyle.ts
- frontend/src/pages/Auth/SignInPageStyle.ts
- frontend/src/pages/Graduate/GraduateOverviewStyle.tsx
- frontend/src/pages/Main/MainStyle.ts
- frontend/src/pages/News/News/NewsCreateStyle.ts
- frontend/src/pages/News/News/NewsDetailStyle.ts
- frontend/src/pages/News/Thesis/ThesisDetailStyle.ts
- frontend/src/styles/GlobalStyle.ts
- 초기화된 폰트 설정 복구
- 기본 폰트(시스템 폰트) -> 나눔스퀘어
- font-weight: 700 -> 800으로 변경
font-weight가 700인 것만 우선적으로 800으로 변경함
Light(300), Regular(400), Bold(700), Extra Bold(800)가 아닌 글자는 어색해보일 수 있음
Closes #299
> [FE] [BUG] 폰트 설정 복구

- backend/src/main/java/org/example/backend/common/exception/ExceptionControllerAdvice.java
- backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java
- backend/src/main/java/org/example/backend/jwt/JWTFilter.java
- file 크기 제한
- 하나의 file 크기는 5MB 까지
- 전체 요청 file 크기는 20MB 까지
- 5MB 넘으면 예외 처리
- jwtFilter 리펙토링
- permit URL이 적용이 안되어서 jwtFilter에서 몇몇 url을 shouldNotFilter 처리
- refreshToken 처리는 특정 경로에서 들어온 요청만 처리하도록 로직 수정
Closes #301
> [BE] file 크기 제한

- frontend/.env.development
- frontend/.env.production
- frontend/src/AppContent.tsx
- frontend/src/components/Banner/MainBanner/MainBanner.tsx
- frontend/src/components/Banner/VideoBanner/index.tsx
- frontend/src/components/Banner/VideoBanner/types.ts
- frontend/src/config/videoConfig.ts
- frontend/src/hooks/useVideosQuality.ts
- frontend/src/utils/videos.ts
https://www.notion.so/tmdtjs/CDN-18a922131c1d802eb7f3fb6205b6801c?pvs=4
본 PR은 비디오 스트리밍 성능 최적화를 위한 Cloudflare CDN 통합 및 비디오 최적화 작업
- 다중 품질 지원 (1080p, 720p)
- 다중 포맷 지원 (MP4, WebM)
- Poster 이미지 추가로 초기 로딩 UX 개선
- 적응형 스트리밍을 위한 소스 구조화
- 3단계 캐싱 전략 구현:
- Cloudflare Edge Cache
- Workers Cache
- R2 Storage (fallback)
- Page Rules 설정으로 장기 캐싱 활성화
- Cache-Control 헤더 최적화
```javascript
headers.set("Cache-Control", "public, max-age=31536000, immutable");
```
- Edge TTL: 1개월
- Browser Cache TTL: 1시간
- 부분 요청(Range requests) 지원
- 글로벌 사용자 지연시간 감소
- 초기 로딩 시간 개선
- 네트워크 대역폭 최적화
- Edge 캐싱으로 원본 서버 부하 감소
- R2 Storage 사용량 최소화
- Workers 실행 횟수 감소
- 끊김 없는 비디오 재생
- 디바이스별 최적화된 품질 제공
- 빠른 초기 로딩
```bash
curl -I https://video-cache-worker.pillow12360.workers.dev/main.mp4
```
- cf-cache-status: HIT 확인
```bash
curl -o …
```
> [FE] [REFACTOR] 메인 동영상 배너 CDN 및 성능최적화

- backend/src/main/java/org/example/backend/board/controller/BoardController.java
- backend/src/main/java/org/example/backend/common/logging/Logging.java
- backend/src/main/java/org/example/backend/common/logging/LoggingAspect.java
스프링 AOP로 logging 적용.
원래는 필터측에 적용하여 전체 로그를 남기려고 했으나 불필요한 로그(단순 조회 등)와 같은 로그는 필요없다고 판단하여 중요 로직(로그인, 생성)에만 적용하기 위해 aop 도입 
```
2025-01-31T20:20:46.598+09:00  INFO 51960 --- [nio-8080-exec-1] o.e.b.common.logging.LoggingAspect       : [REQUEST POST] [PATH /api/board] {"multipartFileList":null,"boardReqDto":
2025-01-31T20:20:46.687+09:00  INFO 51960 --- [nio-8080-exec-1] o.e.b.common.logging.LoggingAspect       : [RESPONSE 200 OK] 11
```
회의 후 필요 api에 어노테이션 적용
@Logging 어노테이션 붙이면 log 가능
로그 저장을 db에 할지 단순 파일에 할지 고민..
Closes #315
> [BE] logging 기능 추가

- backend/src/main/java/org/example/backend/users/controller/admin/AdminController.java
- backend/src/main/java/org/example/backend/users/domain/dto/admin/AdminResDto.java
- backend/src/main/java/org/example/backend/users/service/AdminService.java
> [BE][FEAT] 관리자 비밀번호 수정 기능 구현

- backend/src/main/resources/data.sql
> user통합(admin, member)에 따른 data.sql 수정

- backend/src/main/resources/data.sql
멤버 더미 데이터 추가
"loginId" : "member",
"password" : "1234"
Closes #332
> [BE][FEAT] 멤버 더미 데이터 추가

- frontend/src/AppContent.tsx
- frontend/src/components/Footer/Footer.tsx
- frontend/src/components/ProtectedRoute/ProtectedRoute.tsx
- frontend/src/config/apiConfig.ts
- frontend/src/context/AuthContext.tsx
- frontend/src/pages/Admin/ChangeAdminPassword/ChangeAdminPassword.tsx
> [FIX] [FE] 프로덕션 환경 uri 중복

- backend/src/main/java/org/example/backend/users/exception/member/MemberException.java
- backend/src/main/java/org/example/backend/users/exception/member/MemberExceptionType.java
- backend/src/main/java/org/example/backend/users/service/MemberService.java
멤버 로그인 바이오융합학과로 제한 기능 구현
다른 테스트 할 때 불편하지 않도록 바융과 함께 컴공(임시) 도 넣어놨습니다~
Closes #348
> [BE][FEAT] 멤버 로그인 바이오융합학과로 제한 기능 구현

- backend/src/main/java/org/example/backend/board/domain/dto/BoardResDto.java
- backend/src/main/java/org/example/backend/board/domain/entity/Board.java
- backend/src/main/java/org/example/backend/common/domain/BaseEntity.java
- backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
- backend/src/main/java/org/example/backend/news/domain/dto/NewsResDto.java
- backend/src/main/resources/data.sql
```
2025-02-06T08:22:04.991Z ERROR 1 --- [sejong-auth] [nio-8080-exec-8] o.e.b.c.e.ExceptionControllerAdvice      : 예상하지 못한 예외가 발생했습니다. URI: /api/board/11, 
java.lang.NullPointerException: Cannot invoke "java.time.LocalDateTime.until(java.time.temporal.Temporal, java.time.temporal.TemporalUnit)" because "localDateTime" is null
```
생성, 업데이트 시 조회 안되는 에러 수정.
createDate 삭제
상대 파일 위치 tmp -> var
이유 : 업로드 사진이 계속 지워져서.. 왜 why?
tmp 디렉토리 내의 파일이 자주 지워지는 이유는, /tmp는 임시 파일을 저장하는 공간으로 운영 체제에서 주기적으로 자동으로 정리(삭제)
라네요.. 유닉스 프로그래밍 들었어야..
그래서 자기 컴퓨터에서 파일 업로드 테스트하고 싶으신 분은
application.yml
```
local:
file:
storage:
path: /var/uploads
server:
url: http://localhost:8080
```
추가 하고
```
sudo mkdir -p /var/uploads
sudo chmod -R 777 /var/uploads
```
생성, 권한부여한다음에 진행하시면 잘 생성될겁니다. 배포환경에는 세팅해놨습니다.
```
location /uploads/ { …
```
> [BE] [BUG] 게시판 생성 후 접근 불가 && 파일 첨부 실패

- backend/src/main/java/org/example/backend/users/controller/admin/AdminController.java
> [BE][FEAT] 관리자 기존 비밀번호 검토 API 기능 구현

- backend/src/main/java/org/example/backend/board/controller/BoardController.java
- backend/src/main/java/org/example/backend/common/aop/auth/LoginArgumentResolver.java
- backend/src/main/java/org/example/backend/common/aop/auth/LoginUser.java
- backend/src/main/java/org/example/backend/common/aop/logging/Logging.java
- backend/src/main/java/org/example/backend/common/aop/logging/LoggingAspect.java
- backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
- backend/src/main/java/org/example/backend/reservation/controller/ReservationController.java
- backend/src/main/java/org/example/backend/reservation/domain/Reservation.java
- backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationResDto.java
- backend/src/main/java/org/example/backend/reservation/service/ReservationService.java
직접 코드를 짜니 너무 더러워져서 ArgumentResolver 구현해서 사용했습니다.
Closes #347
> [BE] 유저 ArgumentResolver 구현 & 예약 적용

- backend/src/main/java/org/example/backend/jwt/JWTFilter.java
> [BE][FEAT] refreshToken 으로 새로운 token들 발급

- frontend/package.json
- frontend/src/config/apiConfig.ts
- frontend/src/hooks/queries/useNews.ts
- frontend/src/hooks/queries/useThesis.ts
- frontend/src/pages/Main/components/NewsSection/index.tsx
- frontend/src/pages/News/News/News.tsx
- frontend/src/pages/News/News/NewsCreateStyle.ts
- frontend/src/pages/News/News/NewsDetail.tsx
- frontend/src/pages/News/News/NewsDetailStyle.ts
- frontend/src/pages/News/News/NewsStyle.ts
- frontend/src/pages/News/NoticeBoard/NoticeBoardStyle.ts
- frontend/src/pages/News/NoticeBoard/NoticeDetailStyle.ts
- frontend/src/pages/News/Thesis/ThesisCreate.tsx
- frontend/src/pages/News/Thesis/ThesisDetail.tsx
- frontend/src/pages/News/Thesis/ThesisEdit.tsx
- frontend/src/pages/News/Thesis/ThesisForm.tsx
- frontend/src/pages/News/Thesis/ThesisList.tsx
> [Fix/353] FE 버그 수정

- frontend/src/config/apiConfig.ts
- frontend/src/context/AuthContext.tsx
- frontend/src/pages/Auth/SignInPage.tsx
> [FE][FIX] 로그인 실패 시 (401에러 응답시 login 리다이렉트 로직 제거)

- backend/src/main/resources/data.sql
> [BE] refactor: drop table 제거

- backend/src/main/java/org/example/backend/users/service/MemberService.java
멤버 비밀번호를 데이터베이스에 저장하지 않는 방식으로 수정
Closes #360
> [BE][REFACTOR] 멤버 비밀번호 저장 방식 수정 (DB 미저장 처리)

- backend/src/main/java/org/example/backend/users/exception/member/MemberExceptionType.java
- backend/src/main/java/org/example/backend/users/service/MemberService.java
> [BE][FEAT] 멤버 로그인 예외 처리

- frontend/README.md
- frontend/src/components/Modal/templates/TermsModal.tsx
- frontend/src/index.css
- frontend/tsconfig.json
[FIX] Eslint Prettier 문제 해결 및 재배포
> [FIX] Eslint Prettier 문제 해결 및 재배포

- frontend/src/constants/pageContents.ts
- frontend/src/pages/About/StudentCouncil/StudentCouncil.tsx
> [FE] [CHORE] PM 요구사항 반영

- backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java
- backend/src/main/java/org/example/backend/global/config/web/WebConfig.java
> refactor: cors해결

- backend/src/main/java/org/example/backend/board/domain/entity/Board.java
content 내용 LONGTEXT 설정
기존 내용 삽입 가능하게 설정
Closes #379
> [BE] feat: content LONGTEXT 설정

- .github/workflows/main.yml
- frontend/README.md
#389 fix: CI/CD 배포 오류 해결을 위한 빌드 스크립트 수정 3
> #389 fix: CI/CD 배포 오류 해결을 위한 빌드 스크립트 수정 3

- .github/workflows/main.yml
- frontend/README.md
#389 fix: CI/CD 배포 cache 옵션 제거
> #389 fix: CI/CD 배포 cache 옵션 제거

- .github/workflows/main.yml
- frontend/README.md
#389 fix: CI/CD 배포 React Scripts를 직접 사용
> #389 fix: CI/CD 배포 React Scripts를 직접 사용

- frontend/package.json
- frontend/public/index.html
#389 fix: lint, prettier 스크립트 추가
> #389 fix: lint, prettier 스크립트 추가

- backend/src/main/java/org/example/backend/reservation/domain/Reservation.java
- backend/src/main/java/org/example/backend/reservation/domain/dto/ReservationResDto.java
- backend/src/main/java/org/example/backend/reservation/service/ReservationService.java
- backend/src/main/resources/db/migration/V20250226__init.sql
> [BE] 유저 제거

- frontend/src/pages/About/Faculty/components/common/ProfessorFormStyles.ts
- frontend/src/pages/About/Faculty/components/common/ProfessorFrom.tsx
공통 교수 자식 컴포넌트인 ProfessorForm의 useEffect로 렌더링 시 부모의 initalStatef를 반영하도록 픽스하였습니다.
추후 다른 CRUD 컴포넌트는 Form라이브러리 도입 예정
Closes #429
> [FE][BUG] 수정사항 기존 정보 반영 안됨

- frontend/src/pages/News/News/News.tsx
- frontend/src/pages/News/News/NewsStyle.ts
- 뉴스 이미지 오류 인코딩 로직 추가, 수정
- 뉴스 페이지 스크린샷
> [FE] [FEAT] 뉴스 이미지 오류 수정

- frontend/src/pages/About/Faculty/Professor/index.tsx
- frontend/src/pages/About/Faculty/components/common/ProfessorCard.tsx
1. 메인페이지 숏컷 부분 반응형 로직 개선
2. 교수 수정시 데이터 fetching 안되는 부분
Closes #429
> [Fix/429][FE] 메인페이지 반응형, 교수 수정

- frontend/src/common/SearchComponent.tsx
- frontend/src/common/SearchableBoard.tsx
- frontend/src/config/apiConfig.ts
- frontend/src/constants/pageContents.ts
- frontend/src/features/calendarReservation/components/Calendar/components/RoomInfo/index.tsx
- frontend/src/hooks/queries/useNews.ts
- frontend/src/hooks/queries/useNotice.ts
- frontend/src/hooks/queries/useSeminar.ts
- frontend/src/hooks/queries/useThesis.ts
- frontend/src/pages/News/News/News.tsx
- frontend/src/pages/News/News/NewsCreate.tsx
- frontend/src/pages/News/News/NewsDetail.tsx
- frontend/src/pages/News/News/NewsStyle.ts
- frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
- frontend/src/pages/News/Thesis/ThesisList.tsx
- frontend/src/pages/News/Thesis/ThesisSearchBoard.tsx
- frontend/src/pages/News/Thesis/ThesisStyle.ts
- frontend/src/pages/Seminar/SeminarList.tsx
- frontend/src/types/api/notice.ts
이 PR은 웹사이트의 여러 섹션(세미나, 논문, 공지사항 등)에 일관된 검색 기능을 추가하기 위한 구현을 포함합니다. 공통 검색 컴포넌트를 개발하고 각 섹션의 쿼리 훅을 리팩토링하여 검색 기능을 지원하도록 했습니다.
- **파일 위치**: `src/common/SearchComponent.tsx`
- **목적**: 모든 페이지에서 일관된 검색 입력 UI 제공
- **주요 기능**:
- 검색어 입력 및 제출
- 검색 중 로딩 상태 표시
- Clear 버튼을 통한 입력값 초기화
- 반응형 디자인 지원
- **사용 예시**:
```tsx
<SearchComponent 
onSearch={handleSearch}
placeholder="검색어를 입력하세요"
initialValue={searchKeyword}
searchInProgress={isLoading}
section="seminar"
/>
```
- **파일 위치**: `src/common/SearchableBoard.tsx`
- **목적**: 테이블 형태의 데이터 및 검색 기능을 통합 제공하는 공통 컴포넌트
- **주요 기능**:
- 동적 컬럼 설정 및 데이터 렌더링
- 검색 결과 표시
- 정렬, 페이지네이션 지원
- 검색 초기화 기능
- 빈 결과 및 로딩 상태 처리
- **사용 예시**:
```tsx
<SearchableBoard
title="세미나 목록"
section="seminar"
columns={columns}
items={displayData?.data || []}
isLoading={isLoading}
error={error} …
```
> [FE][Feature/435] 검색기능 CRUD 구현

- frontend/src/pages/News/NoticeBoard/NoticeDetail.tsx
> #435 style: 공지 사항 세부 컨테이너 픽스

- frontend/src/AppContent.tsx
- frontend/src/components/Banner/MainBanner/MainBanner.tsx
- frontend/src/components/Footer/FooterStyle.ts
- frontend/src/components/Header/HeaderStyle.ts
- frontend/src/components/NewsSlider/NewsSlider.tsx
- frontend/src/components/NewsSlider/NewsSliderStyle.ts
- frontend/src/config/apiConfig.ts
- frontend/src/hooks/queries/useNotice.ts
- frontend/src/pages/Graduate/GraduateOverviewStyle.tsx
- frontend/src/pages/Main/Main.tsx
- frontend/src/pages/Main/MainStyle.ts
- frontend/src/pages/Main/components/AnnouncementSection/AnnouncementList.tsx
- frontend/src/pages/Main/components/AnnouncementSection/index.tsx
- frontend/src/pages/Main/components/ButtonListSection/ButtonListSection.tsx
- frontend/src/pages/Main/components/ButtonListSection/ButtonListSectionStyle.ts
- frontend/src/pages/Main/components/VerticalButtonSection/VerticalButtonSectionStyle.ts
- frontend/src/pages/News/News/NewsStyle.ts
- frontend/src/styles/Container.tsx
- frontend/src/styles/theme.ts
- 뉴스 이미지 배경 흰색으로 변경
- 메인페이지 세미나 연사 부분 수정
- 메인페이지 넓이 증가 및 디자인 전체 수정
- 모바일 환경에서 메인페이지 깨지던 부분(Footer, ButtonList, Banner) 수정
- 메인페이지 이미지 슬라이더 모바일 환경에서도 제대로 넘어가도록 수정
* 메인페이지 데스크탑 스크린샷
* 메인페이지 노트북 스크린샷
* 메인페이지 모바일 스크린샷
* 뉴스 배경 스크린샷
Closes #443
> [FE] [FEAT] 전체적인 디자인 깨짐 수정

- frontend/src/hooks/queries/useNotice.ts
- frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
> [FE] [FIX] 공지사항 오류 수정

- frontend/src/pages/About/Faculty/ProfessorEdit/index.tsx
- frontend/src/pages/About/Faculty/components/common/ProfessorFrom.tsx
- frontend/src/pages/About/Faculty/types.ts
- frontend/src/pages/Auth/SignInPageStyle.ts
- frontend/src/types/api/professor.ts
> #435 fix: 교수 수정시 이전 사항 누락 픽스

- frontend/src/config/apiConfig.ts
- frontend/src/hooks/queries/useNotice.ts
- frontend/src/pages/News/NoticeBoard/NoticeBoard.tsx
1. 정렬시 잘못된 요청 버그 해결
2. 번호 표시시 순차적으로 렌더링 되도록 기능 추가
Closes #455
> [Bug][FE] #455 공지사항 정렬 기능 및 번호 순차적 표시

- frontend/public/google7b8b29cb66f52214.html
- frontend/public/robots.txt
- frontend/public/sitemap.xml
> [FE] SEO 관련 파일 생성

- frontend/src/routes/AppRoutes.tsx
> #459 feat: Google Search Console 설정 파일 업로드

- backend/src/main/java/org/example/backend/course/controller/CourseController.java
- backend/src/main/java/org/example/backend/course/domain/dto/req/BSCourseReqDto.java
- backend/src/main/java/org/example/backend/course/domain/dto/req/CourseReqDto.java
- backend/src/main/java/org/example/backend/course/domain/dto/req/MSCourseReqDto.java
- backend/src/main/java/org/example/backend/course/domain/dto/res/BSCourseResDto.java
- backend/src/main/java/org/example/backend/course/domain/dto/res/CourseResDto.java
- backend/src/main/java/org/example/backend/course/domain/dto/res/CourseResDtoFactory.java
- backend/src/main/java/org/example/backend/course/domain/dto/res/MSCourseResDto.java
- backend/src/main/java/org/example/backend/course/domain/entity/BSCourse.java
- backend/src/main/java/org/example/backend/course/domain/entity/Course.java
- backend/src/main/java/org/example/backend/course/domain/entity/CourseType.java
- backend/src/main/java/org/example/backend/course/domain/entity/MSCourse.java
- backend/src/main/java/org/example/backend/course/exception/CourseExceptionType.java
- backend/src/main/java/org/example/backend/course/repository/BSCourseRepository.java
- backend/src/main/java/org/example/backend/course/service/CourseService.java
- backend/src/main/resources/db/migration/V20250403_01__create_course_bs_ms_table.sql
Create
Read All
Read By BS/MS
Read BS Course By 년도, 학년
Read MS Course By 년도
Update
Delete
Closes #462
> 교과과정 년도, 학년, 학기필드 추가

- frontend/public/index.html
-  SEO 테스트 도구 연결을 위한 인증 태그 추가
- 일부 속성 추가
> [FE] SEO 속성 및 테스트 도구 연결

- backend/build.gradle
- backend/src/main/java/org/example/backend/blacklist/service/BlacklistService.java
- backend/src/main/java/org/example/backend/blacklist/service/JwtBlacklistService.java
- backend/src/main/java/org/example/backend/blacklist/service/RedisBlacklistService.java
- backend/src/main/java/org/example/backend/global/config/auth/SecurityConfig.java
- backend/src/main/java/org/example/backend/global/config/redis/RedisConfig.java
- backend/src/main/java/org/example/backend/jwt/JWTFilter.java
- backend/src/main/java/org/example/backend/users/service/MemberService.java
핵심 목표:
MySQL -> Redis 블랙리스트 전환을 유연하게 만들기 위해 인터페이스를 설계하라는 것입니다.
Jwt Blacklist가 사용되는 경우
로그아웃시 access token, refresh token을 blacklist 등록
access token으로 검증이 필요한 admin 작업 시 매번 access token, refresh token이 blacklist 등록되어있는지 확인
감소된 시간: 100ms - 24ms = 76ms
감소율: (76ms / 100ms) * 100 = 76%
76% 개선
Closes #473
> [BE] BlacklistService Mysql -> Redis 변경

- frontend/src/pages/Main/Main.tsx
- frontend/src/pages/Main/components/ButtonListSection/ButtonListSection.tsx
- frontend/src/pages/Main/components/ButtonListSection/data.ts
- frontend/src/pages/Main/components/ButtonListSection/icons.ts
1. 호버시 애니메이션 - 배경색, 아이콘 3d 회전
2. mui 적용하여 안정성 개선
> [Refactor/479] 메인 아이콘 섹션 리스트 디자인 개선
